using System;
using System.Collections.Generic;

namespace MSSQLDBFirst.Models
{
    public partial class IbgReceipt
    {
        public string RcptGuid { get; set; }
        public string RcptNo { get; set; }
        public string Ivno { get; set; }
        public string ServiceType { get; set; }
        public string ProdCode { get; set; }
        public string ProdSn { get; set; }
        public string CustomerGuid { get; set; }
        public string CustomerType { get; set; }
        public string ContactPerson { get; set; }
        public string Sex { get; set; }
        public string ContactAddress { get; set; }
        public string ContactZip { get; set; }
        public string Rcptor { get; set; }
        public DateTime? RcptDate { get; set; }
        public string RepairType { get; set; }
        public string RcptMethod { get; set; }
        public string DeliveryMethod { get; set; }
        public string QuickService { get; set; }
        public string RcptBran { get; set; }
        public string ServiceBran { get; set; }
        public string DeliveryBran { get; set; }
        public string WarrantyPeriod { get; set; }
        public string Chargeable { get; set; }
        public string TroublePhenomenonEx { get; set; }
        public string SpecialRequest { get; set; }
        public string RcptComment { get; set; }
        public string Accessary { get; set; }
        public string Tester { get; set; }
        public DateTime? TestDate { get; set; }
        public string LaboratoryResults { get; set; }
        public string EstmPerson { get; set; }
        public DateTime? EstmContactDate { get; set; }
        public DateTime? EstmReplyDate { get; set; }
        public string RepairPerson { get; set; }
        public DateTime? RepairDate { get; set; }
        public string RepairContent { get; set; }
        public decimal? RepairTime { get; set; }
        public string RepairRank { get; set; }
        public string ReRepairType { get; set; }
        public string ProdExchange { get; set; }
        public string ExchangeReason { get; set; }
        public string Srflag { get; set; }
        public string Srtype { get; set; }
        public string Srcomment { get; set; }
        public string Srquality { get; set; }
        public string ReturnType { get; set; }
        public string DisRepairReason { get; set; }
        public int? ReleaseCount { get; set; }
        public string QuickServiceFinished { get; set; }
        public decimal? DeliveryTime { get; set; }
        public DateTime? TargetRepairDate { get; set; }
        public string ResultCheckPerson { get; set; }
        public DateTime? ResultCheckDate { get; set; }
        public decimal? LaborCharge { get; set; }
        public decimal? TestCharge { get; set; }
        public decimal? PostFee { get; set; }
        public decimal? OtherCharge { get; set; }
        public string OtherChargeReason { get; set; }
        public decimal? DiscountAmt { get; set; }
        public string DiscountReason { get; set; }
        public string DiscountComment { get; set; }
        public decimal? EstmLaborCharge { get; set; }
        public decimal? EstmTestCharge { get; set; }
        public decimal? EstmPostFee { get; set; }
        public decimal? EstmOtherCharge { get; set; }
        public string EstmOtherChargeReason { get; set; }
        public decimal? EstmDiscountAmt { get; set; }
        public string EstmDiscountReason { get; set; }
        public string EstmDiscountComment { get; set; }
        public string FinishedContactPerson { get; set; }
        public DateTime? FinishedContactDate { get; set; }
        public string FinishedContactComment { get; set; }
        public string ClosePerson { get; set; }
        public DateTime? CloseDate { get; set; }
        public string CloseComment { get; set; }
        public string PostPerson { get; set; }
        public DateTime? PostDate { get; set; }
        public string PostComment { get; set; }
        public string StaCode { get; set; }
        public decimal? EstmDiscountRate { get; set; }
        public decimal? DiscountRate { get; set; }
        public string OddHandlingType { get; set; }
        public int? AvailDigit { get; set; }
        public string EstmDiscountRateOwcomment { get; set; }
        public string DiscountRateOwcomment { get; set; }
        public string RecordId { get; set; }
        public DateTime? CreateDate { get; set; }
        public string Creator { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string Updator { get; set; }
        public string RecordVersion { get; set; }
        public string ViaBran { get; set; }
        public decimal? TaxRate { get; set; }
        public string Wait4PartsContactPerson { get; set; }
        public DateTime? Wait4PartsContactDate { get; set; }
        public string Wait4PartsContactMemo { get; set; }
        public string BranCodeMgt { get; set; }
        public string ProdSta { get; set; }
        public string StockRepairRank { get; set; }
        public DateTime? EstmReplyDateOriginal { get; set; }
    }
}
